apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-onedata
  labels:
    name: pv-onedata
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  storageClassName: onedata
  csi:
    driver: csi-onedata
    volumeHandle: data-id-onedata
    volumeAttributes:
      host: host
      token: token
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-onedata
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: onedata
  selector:
    matchLabels:
      name: pv-onedata
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: maersk/nginx
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/www
        name: v-onedata
  volumes:
  - name: v-onedata
    persistentVolumeClaim:
      claimName: pvc-onedata
