# This YAML file contains driver-registrar & csi driver nodeplugin API objects
# that are necessary to run CSI nodeplugin for onedata
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-nodeplugin-onedata
  namespace: csi-onedata
spec:
  selector:
    matchLabels:
      app: csi-nodeplugin-onedata
  template:
    metadata:
      labels:
        app: csi-nodeplugin-onedata
    spec:
      serviceAccountName: csi-nodeplugin-onedata
      hostNetwork: true
      containers:
        - name: node-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.0.2
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/csi-onedata /registration/csi-onedata-reg.sock"]
          args:
            - --v=5
            - --csi-address=/plugin/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/csi-onedata/csi.sock
#            - --kubelet-registration-path=/var/snap/microk8s/common/var/lib/kubelet/plugins/csi-onedata/csi.sock
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: registration-dir
              mountPath: /registration
        - name: onedata
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: jhandl/csi-onedata:latest
          args:
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
#              mountPath: /var/snap/microk8s/common/var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi-onedata
#            path: /var/snap/microk8s/common/var/lib/kubelet/plugins/csi-onedata
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
#            path: /var/snap/microk8s/common/var/lib/kubelet/pods
            type: Directory
        - hostPath:
            path: /var/lib/kubelet/plugins_registry
#            path: /var/snap/microk8s/common/var/lib/kubelet/plugins_registry
            type: DirectoryOrCreate
          name: registration-dir
