# This YAML file contains attacher & csi driver API objects that are necessary
# to run external CSI attacher for onedata

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-controller-onedata
  namespace: csi-onedata
spec:
  serviceName: "csi-controller-onedata"
  replicas: 1
  selector:
    matchLabels:
      app: csi-controller-onedata
  template:
    metadata:
      labels:
        app: csi-controller-onedata
    spec:
      serviceAccountName: csi-controller-onedata
      containers:
        - name: csi-attacher
          image: k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-cluster-driver-registrar
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.4.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/csi-onedata/csi.sock"
#            - "--kubelet-registration-path=/var/snap/microk8s/common/var/lib/kubelet/plugins/csi-onedata/csi.sock"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: onedata
          #image: jhandl/csi-onedata:v20.02.19
          image: jhandl/csi-onedata:v21.02.2
          args :
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /plugin
      volumes:
        - name: socket-dir
          emptyDir:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory

